### ISSUE TITLE
Endpoint timeout lost on reboot of worker hosting NSE and k8s-registry

### ISSUE THREAD

**Issue by zolug** [networkservicemesh/cmd-registry-k8s#376]
When an NSE and the k8s-registry handling its registration are both hosted by the same worker, then loss of said worker will result in the NSE Custom Resource to remain in etcd.

problem is similar to: https://github.com/networkservicemesh/cmd-registry-k8s/issues/158

reproduction with Kind (1 controller, 2 workers):
- startup nsm with k8s-registry
- create an NSE on a worker with k8s-registry
- stop the docker container of the worker hosting NSE and registry
- check the nse custom resources

Would be nice to have some "garbage collection" like feature in k8s-registry to handle dangling nses.

**Comment by richardstone** [comment]
Hi @edwarnicke and @denis-tingaikin 

Could you please prioritise this ticket as it's blocking our progress as of now.

Thanks!

**Comment by edwarnicke** [comment]
@denis-tingaikin Could you have a look at this?

**Comment by richardstone** [comment]
Hi,

Now we are on NSM 1.6.1 and uplifting might be a bit of pain. Is there any chance of back-porting the solution to 1.6 track?

**Comment by denis-tingaikin** [comment]
theoretically  it's possible to release v1.6.2 that will include the needed fix.

@edwarnicke WDYT?

**Comment by richardstone** [comment]
@denis-tingaikin
That would be really great!

**Comment by edwarnicke** [comment]
@denis-tingaikin If its not to heavy a lift, I'm fine with doing a v1.6.2

**Comment by LionelJouin** [comment]
Here is a way to reproduce the problem (So same as this: https://github.com/networkservicemesh/cmd-registry-k8s/issues/158):
```
kubectl apply -k https://github.com/networkservicemesh/deployments-k8s/examples/spire/single_cluster/?ref=v1.8.0
kubectl apply -k https://github.com/networkservicemesh/deployments-k8s/examples/basic?ref=v1.8.0
kubectl apply -k https://github.com/networkservicemesh/deployments-k8s/examples/use-cases/Kernel2Ethernet2Kernel?ref=v1.8.0

# (It is this example until now: https://github.com/networkservicemesh/deployments-k8s/tree/v1.8.0/examples/use-cases/Kernel2Ethernet2Kernel)

kubectl delete ns ns-kernel2ethernet2kernel
registry=$(kubectl get pods --selector="app=registry" -n nsm-system --no-headers=true | awk '{print $1}')
kubectl delete pods -n nsm-system $registry
```

And now you can see the NSE will never be removed (kubectl get nse -n nsm-system) even after 10 minutes (the default timeout).

Here is one solution to this problem:
```
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: registry-k8s-gc
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: registry-k8s-sa
          containers:
          - name: registry-k8s-gc
            image: bitnami/kubectl:latest
            command: ["/bin/bash"]
            args:
            - "-c"
            - |
              nses=$(kubectl get nse -n nsm-system --no-headers=true | awk '{print $1}')
              current=$(date +%s)
              while IFS= read -r nse; do
                  nse_expiration=$(kubectl get nse $nse -n nsm-system -o json | jq -r '.spec.expiration_time.seconds')
                  if (( current > nse_expiration )); then
                    kubectl delete nse -n nsm-system $nse
                  fi
              done <<< "$nses"
          restartPolicy: OnFailure
```
